//Session related Actions
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const ORDER_HISTORY_LOADING = 'ORDER_HISTORY_LOADING';
export const ORDER_HISTORY_FAILURE = 'ORDER_HISTORY_FAILURE';
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_RESET_STATE = 'ORDER_HISTORY_RESET_STATE';

export const ORDER_STATUS_SUCCESS = 'ORDER_STATUS_SUCCESS';
export const ORDER_STATUS_FAILURE = 'ORDER_STATUS_FAILURE';

export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';

export const GET_ITEM_LOADING = 'GET_ITEM_LOADING';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_RESET_STATE = 'GET_ITEM_RESET_STATE';

export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const NOTIFICATION_RESET_STATE = 'NOTIFICATION_RESET_STATE';
export const NOTIFICATION_SUCCESS_REAL_TIME = 'NOTIFICATION_SUCCESS_REAL_TIME';

export const ADDRESS_LOADING = 'ADDRESS_LOADING';
export const ADDRESS_FAILURE = 'ADDRESS_FAILURE';
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS';
export const ADDRESS_RESET_STATE = 'ADDRESS_RESET_STATE';