export default {
  currency: '€',
  onboardingTitle1: 'Food Corner is Where Your Comfort Food Lives',
  login: 'Log in',
  signup: 'Sign up',
  or: 'OR',
  start: "Sign in",
  loginText: 'Sign in to continue',
  phonePlaceholder: 'Phone number',
  emailPlaceholder: 'Enter your email',
  password: 'Password',
  noAccount: "Don't have an account, ",
  signupnow: 'SIGNUP NOW',
  loginnow: 'LOGIN NOW',
  signupHeading: 'Get ready to enjoy food services',
  firstName: 'First Name',
  lastName: 'Last Name',
  restaurant: 'Restuarant',
  passwordHeading: 'ALMOST DONE',
  confirmPassword: 'Confirm Password',
  forgot: 'Reset Password',
  forgotPassword: 'Forgot your password?',
  forgotConfermation: ' Password Confermation',
  reset: 'Enter your email to receive reset password link',
  resetButton: 'RESET',
  next: 'Next',
  placeOrder: 'Place Order',
  delivery: 'Delivery',
  pickup: 'Pick Up',
  dinein: 'Dine In',
  contactInfo: 'Contact Info',
  deliveryTime: 'Delivery Time',
  pickUpDateTime: 'Pick Up Date and Time',
  wallet: 'Wallet',
  card: 'Card',
  cash: 'Cash',
  createPassword: 'Create new password',
  noPeoplePlaceholder: 'No. of People',
  datePlaceholder: 'Date',
  timePlaceholder: 'Start Time',
  contactNoPlaceholder: 'Contact No.',
  about: 'About',
  addAdress: 'Add Address',
  selectLocation: 'Selected Location',
  street: 'Street',
  floorBuilding: 'Floor # / Building',
  noteToRider: 'Note to Rider',
  saveAddress: 'Save Address',
  ratingUpdated: 'Rating Updated',
  addresses: 'Addresses',
  selectLocationa: 'Select Location',
  settings: 'Settings',
  notifications: 'Notifications',
  logOut: 'Log Out',
  filters: 'Filters',
  postcode: 'Postcode',
  nearestMe: 'Nearest Me',
  homeScreen: 'Home Screen',
  myRewards: 'My Rewards',
  myAddress: 'My Address',
  homeAdress: 'Current Address: Home',
  myDetails: 'My Details',
  changePassword: 'Change Password',
  profile: 'Profile',
  rate: 'Rate',
  feedback: 'Leave Feedback',
  allRestaurants: 'All Restaurants',
  reviews: 'Reviews',
  myDetailsa: 'My Details',
  firstNamea: 'First Name',
  lastNamea: 'Last Name',
  email: 'Email',
  emailSmallLatter:'email',
  mobile: 'Mobile No.',
  update: 'Update',
  type: 'Type',
  orderTitle: 'Orders',
  payments: 'Payments',
  paymentType: 'Payment Type',
  OrderDetail: 'Order Detail',
  deliveryCharges: 'Delivery Charges: £',
  support: 'Support',
  miles:'miles',
  total:'Total',
  justNow: 'Just Now',
  orderId: 'Order ID: ',
  nisaSultan :'nisa Sultan',
  nisaSultanAddress: 'MM alam road nisa sultan',
  discountReward: '10% discount on all Burgers, Pizza, Biryani items',
  subTotal: ' Subtotal',
  deliveryText: 'Delivery (incl. tax)',
  totalCharges: 'Total Charges',
  viewYourCart: 'View your Cart',
  openingTimings: 'Opening Timings',
  openinngDays: 'Opening Days',
  lorem1: 'Lorem ipsum dolor sit amet',
  lorem2: 'The lorem ipsum is based on De finibus bonorum et malorum . The lorem ipsum gets its name from the Latin phrase',
  lorem3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum.',
  select: 'Select',
  paymentMethod: 'Payment Method',
  changePassword: 'Change Password',
  changePasswordText: 'Please change your password here',
  noDataAvailable: ' No data available!',
  sortBy: 'Sort By',
  price: 'Price',
  inventory: 'Inventory',
  currentLocation: 'Current Location',
  totalBill: 'Total x',
  rewardTitle: 'Rewards',
  history: 'History',
  myAccount: 'My Account',
  paid: 'Paid',
  addons: 'Addons',
  x: 'x',
  addPayment: 'Add Payment',
  saveCard: 'Save Card',
  thankYou: 'THANKYOU!',
  passwordChanged: 'Password Changed',
  loginSuccess: 'You have successfully changed your password! Try your new login.',
  submit: 'Submit',
  skip: 'Skip',
  skipCapitalCase: 'SKIP',
  gender: 'Gender',
  home: 'Home',
  work: 'Work',
  other: 'Other',
  item: 'item',
  itemsTotal: 'Items Total',
  label: 'Lable',
  cart: 'Cart',
  promoCode: 'Promo Code',
  placeOrderCardText1: 'YOU HAVE SUCCESSFULLY',
  placeOrderCardText2: 'PLACED YOUR ORDER',
  oldPassword: 'Old Password',
  newPassword: 'New password',
  confirmPassword: 'Confirm Password',
  changePassword: 'Change Password',
  changePasswordCardText1: 'YOU HAVE SUCCESSFULLY',
  changePasswordCardText2: 'CHANGED YOUR PASSWORD',
  celories250: '250 kcal',
  search: 'Search...',
  mobNumber: '4242 4242 4242 4242',
  star: 'star',
  send: 'Send',
  fourPoint9: '4.9',
  twentyMin: '20 min',
  facebookEmailPostFix:'@foodlea.com',
  emailSent: 'Email Sent',
  passwordResetEmail: 'We have sent you an email with reset password link. Open and recover your password',
  changeYourOrderStatus: 'Change your Order Status',
  status: 'Status:',
  preparingMinutes: 'Preparing Minutes',
  deliveryMinutes: 'Delivery Minutes',
  changeStatus: 'Change Status',
  dateAndTime: 'Create date & time: ',
  cancelOrder: 'Cancel Order',
  service: 'Service',
  payment: 'Payment',
  success: 'success',
  trackOrderDetails: 'Track Order Details',
  orderDetails: 'ORDER DETAILS',
  pending: 'Pending',
  preparing: 'Preparing',
  shipping: 'Shipping',
  ready: 'Ready',
  delivered: 'Delivered',
  pickUp: 'PickUp',
  addItem: 'Add Item',
};
