export default {
  logo: require('../assets/images/logo.png'),
  splash: require('../assets/images/splash.png'),
  user: require('../assets/images/user.jpg'),
  login: require('../assets/images/login.png'),
  man: require('../assets/images/man.png'),
  accounts: require('../assets/images/accounts.png'),
  settings: require('../assets/images/settings.png'),
  history: require('../assets/images/history.png'),
  inventory: require('../assets/images/inventory.png'),
  orders: require('../assets/images/orders.png'),
  ordersSelected: require('../assets/images/orderSelected.png'),
  ordersDrawer: require('../assets/images/ordersDrawer.png'),
  emailIcon: require('../assets/images/emailicon.png'),
  passwordChange: require('../assets/images/passwordChange.png'),
  accountsUnselected: require('../assets/images/profileUnselected.png'),
  settingsUnselected: require('../assets/images/settingsunselected.png'),
  historyUnselected: require('../assets/images/historyUnselected.png'),
  inventoryUnselected: require('../assets/images/inventoryUnselected.png'),
  ordersUnselected: require('../assets/images/ordersUnselected.png'),
  burger: require('../assets/images/burger-1.png'),
  activeOrders: require('../assets/images/activeOrders.png'),
  completedOrders: require('../assets/images/completedOrders.png'),
  pendingOrders: require('../assets/images/pendingOrders.png'),
  totalOrders: require('../assets/images/totalOrders.png'),
  
};
