export default {
  logo: require('../assets/images/logo.png'),
  splash: require('../assets/images/splash.png'),
  user: require('../assets/images/user.jpg'),
  login: require('../assets/images/login.png'),
  man: require('../assets/images/man.png'),
  accounts: require('../assets/images/accounts.png'),
  settings: require('../assets/images/settings.png'),
  history: require('../assets/images/history.png'),
  inventory: require('../assets/images/inventory.png'),
  orders: require('../assets/images/orders.png'),
  ordersSelected: require('../assets/images/orderSelected.png'),
  ordersDrawer: require('../assets/images/ordersDrawer.png'),
  emailIcon: require('../assets/images/emailicon.png'),
  passwordChange: require('../assets/images/passwordChange.png'),
  accountsUnselected: require('../assets/images/profileUnselected.png'),
  settingsUnselected: require('../assets/images/settingsunselected.png'),
  historyUnselected: require('../assets/images/historyUnselected.png'),
  inventoryUnselected: require('../assets/images/inventoryUnselected.png'),
  ordersUnselected: require('../assets/images/ordersUnselected.png'),
  burger: require('../assets/images/burger-1.png'),
  activeOrders: require('../assets/images/activeOrders.png'),
  completedOrders: require('../assets/images/completedOrders.png'),
  pendingOrders: require('../assets/images/pendingOrders.png'),
  totalOrders: require('../assets/images/totalOrders.png'),
  food: require('../assets/images/food.png'),
  man2: require('../assets/images/man2.png'),
  man3: require('../assets/images/man3.png'),
  pencil: require('../assets/images/pencil.png'),
  
  currency: require('../assets/images/currency.png'),
  orderLimit: require('../assets/images/orderLimit.png'),
  restaurantDetails: require('../assets/images/restaurantDetails.png'),
  serviceCharges: require('../assets/images/serviceCharges.png'),
  timings: require('../assets/images/timmings.png'),
  ok: require('../assets/images/ok.png'),
  deal: require('../assets/images/deal.png'),
  category: require('../assets/images/category.png'),
  addons: require('../assets/images/addons.png'),
  menu: require('../assets/images/menu.png'),
  statistics: require('../assets/images/statistics.png'),
  allOrders: require('../assets/images/allOrders.png'),
  beefBurger: require('../assets/images/beefBurger.png'),
  rating: require('../assets/images/rating.png'),
  changePassword: require('../assets/images/changePassword.png'),
  myDetails: require('../assets/images/myDetails.png'),

};
