export default {
  logo: require('../assets/images/logo.png'),
  splash: require('../assets/images/splash.png'),
  user: require('../assets/images/user.jpg'),
  onboarding1: require('../assets/images/onboarding1.png'),
  onboarding2: require('../assets/images/onboarding2.png'),
  google: require('../assets/images/google.png'),
  facebook: require('../assets/images/facebook.png'),
  apple: require('../assets/images/apple.png'),
  restaurantImg: require('../assets/images/burger1.jpeg'),
  menuImg: require('../assets/images/burger.png'),
  aboutImg: require('../assets/images/bg.png'),
  thanks: require('../assets/images/thankyou.png'),
  star: require('../assets/images/star.png'),
  mapbox: require('../assets/images/mapbox.jpeg'),
  marker: require('../assets/images/marker.png'),
  currentLoc: require('../assets/images/currentLoc.png'),
  checkout: require('../assets/images/checkout.png'),
  close: require('../assets/images/close.png'),
  reward: require('../assets/images/reward.png'),
  rewardBadge: require('../assets/images/rewardbadge.png'),
};
